### ISSUE TITLE
Login template

### ISSUE THREAD

**Issue by samazaphikel** [discolabs/auth_demo#1]
Hi,
Im trying to use this example.

In my configuration, I use Python 3.7.3 and Django 2.2.3

I changed in the settings `MIDDLEWARE_CLASSES` to `MIDDLEWARE`

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            PROJECT_PATH + '/templates/',
            ...
```

But when I try to install on the demo shopify, the Login ask me for the store url and after click on **Install** I get this error message on Django

> [20/Jul/2019 09:51:30] "GET /accounts/login/?next=/ HTTP/1.1" 200 347
> Internal Server Error: /accounts/login/
> Traceback (most recent call last):
>   File "/home/sebastian/PycharmProjects/auth_demo/venv/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
>     return self.get(**kwargs), False
>   File "/home/sebastian/PycharmProjects/auth_demo/venv/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
>     self.model._meta.object_name
> auth_app.models.AuthAppShopUser.DoesNotExist: AuthAppShopUser matching query does not exist.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/sebastian/PycharmProjects/auth_demo/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/sebastian/PycharmProjects/auth_demo/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
>     return Database.Cursor.execute(self, query, params)
> sqlite3.IntegrityError: NOT NULL constraint failed: auth_app_authappshopuser.last_login
> 

I changed manually in the SQLite3 last_login NOT NULL false

But the next problem is, after installation, I get a Error 404

```

Page not found (404)
Request Method:	GET
Request URL:	https://5cdf423d.ngrok.io/login/finalize/auth_app.views.home
Using the URLconf defined in mysite.urls, Django tried these URL patterns, in this order:

login/ ^finalize/$
login/ ^authenticate/$
login/ ^$
^$
The current path, login/finalize/auth_app.views.home, didn't match any of these.
```

What do I have to do to solve the problem?
I didnt chnaged anything from auth_app

**Comment by scottpersinger** [comment]
For anyone that finds this, this error comes from the default value of Django `LOGIN_URL` being equal to `/accounts/login'. I just had to set `LOGIN_URL=/login` in my settings.
